# Generated by Django 4.1 on 2022-09-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timetaken',
            field=models.CharField(max_length=100),
        ),
    ]
