# Generated by Django 4.1 on 2022-09-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_profile_timetaken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
